-- MySQL Script generated by MySQL Workbench
-- Tue Apr 24 09:32:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Skins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Skins` (
  `idSkins` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `preco` FLOAT NULL,
  `quantidade` INT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idSkins`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `idInventario` INT NOT NULL,
  `quantidadeSkin` INT NULL,
  PRIMARY KEY (`idInventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skins_has_Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Skins_has_Inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Skins_has_Inventario` (
  `Skins_idSkins` INT NOT NULL,
  `Inventario_idInventario` INT NOT NULL,
  PRIMARY KEY (`Skins_idSkins`, `Inventario_idInventario`),
  INDEX `fk_Skins_has_Inventario_Inventario1_idx` (`Inventario_idInventario` ASC),
  INDEX `fk_Skins_has_Inventario_Skins1_idx` (`Skins_idSkins` ASC),
  CONSTRAINT `fk_Skins_has_Inventario_Skins1`
    FOREIGN KEY (`Skins_idSkins`)
    REFERENCES `mydb`.`Skins` (`idSkins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Skins_has_Inventario_Inventario1`
    FOREIGN KEY (`Inventario_idInventario`)
    REFERENCES `mydb`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario_has_Skins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inventario_has_Skins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inventario_has_Skins` (
  `Inventario_idInventario` INT NOT NULL,
  `Skins_idSkins` INT NOT NULL,
  PRIMARY KEY (`Inventario_idInventario`, `Skins_idSkins`),
  INDEX `fk_Inventario_has_Skins_Skins1_idx` (`Skins_idSkins` ASC),
  INDEX `fk_Inventario_has_Skins_Inventario1_idx` (`Inventario_idInventario` ASC),
  CONSTRAINT `fk_Inventario_has_Skins_Inventario1`
    FOREIGN KEY (`Inventario_idInventario`)
    REFERENCES `mydb`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_has_Skins_Skins1`
    FOREIGN KEY (`Skins_idSkins`)
    REFERENCES `mydb`.`Skins` (`idSkins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Skins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User_has_Skins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Skins` (
  `User_idUser` INT NOT NULL,
  `Skins_idSkins` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Skins_idSkins`),
  INDEX `fk_User_has_Skins_Skins1_idx` (`Skins_idSkins` ASC),
  INDEX `fk_User_has_Skins_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_User_has_Skins_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Skins_Skins1`
    FOREIGN KEY (`Skins_idSkins`)
    REFERENCES `mydb`.`Skins` (`idSkins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
